<a href="https://colab.research.google.com/github/JeJe620/NYU-SUMMER-2021/blob/main/Regression_Discontinuity_%26_DiD_sections.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preparation

Story Background: https://www.gemini.com/cryptopedia/the-dao-hack-makerdao

Event: July 20, 2016, at block 192,000

[Data Metrics](https://github.com/coinmetrics-io/data/blob/master/csv/metrics.csv)

In [ ]:
import pandas as pd
import numpy as np

###import the data for Ethereum

In [ ]:
df_eth=pd.read_csv("https://raw.githubusercontent.com/coinmetrics-io/data/master/csv/eth.csv")
df_eth.head()

         time  AdrActCnt  ...  VtyDayRet180d  VtyDayRet30d
0  2015-07-30     9206.0  ...            NaN           NaN
1  2015-07-31      424.0  ...            NaN           NaN
2  2015-08-01      413.0  ...            NaN           NaN
3  2015-08-02      432.0  ...            NaN           NaN
4  2015-08-03      444.0  ...            NaN           NaN

[5 rows x 139 columns]

In [ ]:
df_eth['time']=pd.to_datetime(df_eth['time'])
df_eth.dtypes

time                datetime64[ns]
AdrActCnt                  float64
AdrBal1in100KCnt           float64
AdrBal1in100MCnt           float64
AdrBal1in10BCnt            float64
                         ...
TxTfrValMedNtv             float64
TxTfrValMedUSD             float64
VelCur1yr                  float64
VtyDayRet180d              float64
VtyDayRet30d               float64
Length: 139, dtype: object

In [ ]:
df_eth['Type'] = 'eth'
df_eth.head()

        time  AdrActCnt  AdrBal1in100KCnt  ...  VtyDayRet180d  VtyDayRet30d  Type
0 2015-07-30     9206.0            5685.0  ...            NaN           NaN   eth
1 2015-07-31      424.0            5692.0  ...            NaN           NaN   eth
2 2015-08-01      413.0            5699.0  ...            NaN           NaN   eth
3 2015-08-02      432.0            5708.0  ...            NaN           NaN   eth
4 2015-08-03      444.0            5715.0  ...            NaN           NaN   eth

[5 rows x 140 columns]

### Import the Data for Ethereum Classic

In [ ]:
df_etc=pd.read_csv("https://raw.githubusercontent.com/coinmetrics-io/data/master/csv/etc.csv")
df_etc.head()

         time  AdrActCnt  ...  VtyDayRet180d  VtyDayRet30d
0  2016-07-20    21680.0  ...            NaN           NaN
1  2016-07-21    17037.0  ...            NaN           NaN
2  2016-07-22    13208.0  ...            NaN           NaN
3  2016-07-23     9838.0  ...            NaN           NaN
4  2016-07-24    14910.0  ...            NaN           NaN

[5 rows x 134 columns]

In [ ]:
### change to dateime
df_etc['time']=pd.to_datetime(df_etc['time'])
df_etc.dtypes

time                datetime64[ns]
AdrActCnt                  float64
AdrBal1in100KCnt           float64
AdrBal1in100MCnt           float64
AdrBal1in10BCnt            float64
                         ...
TxTfrValMedNtv             float64
TxTfrValMedUSD             float64
VelCur1yr                  float64
VtyDayRet180d              float64
VtyDayRet30d               float64
Length: 134, dtype: object

In [ ]:
df_etc['Type'] = 'etc'
df_etc.head()

        time  AdrActCnt  AdrBal1in100KCnt  ...  VtyDayRet180d  VtyDayRet30d  Type
0 2016-07-20    21680.0            5491.0  ...            NaN           NaN   etc
1 2016-07-21    17037.0            5471.0  ...            NaN           NaN   etc
2 2016-07-22    13208.0            5497.0  ...            NaN           NaN   etc
3 2016-07-23     9838.0            5499.0  ...            NaN           NaN   etc
4 2016-07-24    14910.0            5304.0  ...            NaN           NaN   etc

[5 rows x 135 columns]

# Regression Discontinguity

https://youtu.be/TfKwgGT2fSM

### create the identifier varaible for Dao Hack

In [ ]:
from datetime import date

In [ ]:
df_eth ['After_DaoHack'] =df_eth['time'].apply(lambda x: 1 if x>= date(2016,7,20) else 0)
df_eth[df_eth.time.dt.date>=date(2016,7,18)].head()

          time  AdrActCnt  AdrBal1in100KCnt  ...  VtyDayRet30d  Type  After_DaoHack
354 2016-07-18    18988.0            6564.0  ...      0.056129   eth              0
355 2016-07-19    26614.0            5492.0  ...      0.054430   eth              0
356 2016-07-20    25428.0            5730.0  ...      0.055036   eth              1
357 2016-07-21    22477.0            5866.0  ...      0.051285   eth              1
358 2016-07-22    24563.0            5917.0  ...      0.058285   eth              1

[5 rows x 141 columns]

In [ ]:
df_eth['days']=df_eth.index
df_eth.head()

        time  AdrActCnt  AdrBal1in100KCnt  ...  Type  After_DaoHack  days
0 2015-07-30     9206.0            5685.0  ...   eth              0     0
1 2015-07-31      424.0            5692.0  ...   eth              0     1
2 2015-08-01      413.0            5699.0  ...   eth              0     2
3 2015-08-02      432.0            5708.0  ...   eth              0     3
4 2015-08-03      444.0            5715.0  ...   eth              0     4

[5 rows x 142 columns]

### normalize the data

In [ ]:
df_eth['days'][df_eth.time.dt.date==date(2016,7,20)]

356    356
Name: days, dtype: int64

In [ ]:
df_eth['days']=df_eth['days']-356
df_eth[df_eth.time.dt.date>=date(2016,7,18)].head()

          time  AdrActCnt  AdrBal1in100KCnt  ...  Type  After_DaoHack  days
354 2016-07-18    18988.0            6564.0  ...   eth              0    -2
355 2016-07-19    26614.0            5492.0  ...   eth              0    -1
356 2016-07-20    25428.0            5730.0  ...   eth              1     0
357 2016-07-21    22477.0            5866.0  ...   eth              1     1
358 2016-07-22    24563.0            5917.0  ...   eth              1     2

[5 rows x 142 columns]

## create the regression function

https://www.statsmodels.org/stable/index.html

In [ ]:
 import statsmodels.api as sm
 import statsmodels.formula.api as smf

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
results = smf.ols('VtyDayRet30d ~ 1+ After_DaoHack +days+TxTfrValAdjUSD ', data=df_eth).fit()

In [ ]:
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           VtyDayRet30d   R-squared:                       0.233
Model:                            OLS   Adj. R-squared:                  0.232
Method:                 Least Squares   F-statistic:                     214.2
Date:                Sat, 26 Jun 2021   Prob (F-statistic):          2.44e-121
Time:                        07:36:45   Log-Likelihood:                 5099.7
No. Observations:                2118   AIC:                        -1.019e+04
Df Residuals:                    2114   BIC:                        -1.017e+04
Df Model:                           3
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          0.0818      0.001     66.166      0.000       0.079       0.084
After_DaoHack     -0.0223      0.002    -13.078      0.000      -0.026      -0.019
days           -9.745e-06   1.07e-06     -9.077      0.000   -1.19e-05   -7.64e-06
TxTfrValAdjUSD  1.114e-12   1.29e-13      8.617      0.000     8.6e-13    1.37e-12
==============================================================================
Omnibus:                      302.493   Durbin-Watson:                   0.052
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              568.964
Skew:                           0.892   Prob(JB):                    2.82e-124
Kurtosis:                       4.807   Cond. No.                     1.83e+10
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.83e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
results = smf.ols('VtyDayRet30d ~ 1+ After_DaoHack + days +After_DaoHack*days +TxTfrValAdjUSD', data=df_eth).fit()

In [ ]:
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           VtyDayRet30d   R-squared:                       0.248
Model:                            OLS   Adj. R-squared:                  0.246
Method:                 Least Squares   F-statistic:                     174.0
Date:                Sat, 26 Jun 2021   Prob (F-statistic):          6.18e-129
Time:                        07:36:45   Log-Likelihood:                 5120.1
No. Observations:                2118   AIC:                        -1.023e+04
Df Residuals:                    2113   BIC:                        -1.020e+04
Df Model:                           4
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept              0.0683      0.002     28.106      0.000       0.064       0.073
After_DaoHack         -0.0093      0.003     -3.506      0.000      -0.014      -0.004
days               -9.438e-05   1.33e-05     -7.120      0.000      -0.000   -6.84e-05
After_DaoHack:days  8.518e-05   1.33e-05      6.406      0.000    5.91e-05       0.000
TxTfrValAdjUSD      1.088e-12   1.28e-13      8.494      0.000    8.37e-13    1.34e-12
==============================================================================
Omnibus:                      309.665   Durbin-Watson:                   0.051
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              607.051
Skew:                           0.894   Prob(JB):                    1.52e-132
Kurtosis:                       4.919   Cond. No.                     3.24e+10
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.24e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

# Difference in Difference

https://towardsdatascience.com/causal-inference-101-difference-in-differences-1fbbb0f55e85

### prepare the datasets

In [ ]:
Columns =["time","VtyDayRet30d","TxTfrValAdjUSD","FeeMedUSD","RevUSD","GasLmtTxMean","Type"]
df_eth =df_eth[Columns]
df_etc =df_etc[Columns]

In [ ]:
df_etc =df_etc.dropna()
df_etc.head()

         time  VtyDayRet30d  TxTfrValAdjUSD  ...        RevUSD   GasLmtTxMean  Type
35 2016-08-24      0.292737    5.313273e+06  ...  47593.726863  197837.042436   etc
36 2016-08-25      0.124512    4.639205e+06  ...  45558.072710  204431.309179   etc
37 2016-08-26      0.094313    6.074296e+06  ...  47088.940529  208950.209837   etc
38 2016-08-27      0.093886    6.293356e+06  ...  44866.326999  175090.831416   etc
39 2016-08-28      0.093662    3.258098e+06  ...  43283.800478  187384.163307   etc

[5 rows x 7 columns]

In [ ]:
df_eth =df_eth[df_eth.time.dt.date>=date(2016,7,25)]
df_etc =df_etc[df_etc.time.dt.date>=date(2016,7,25)]

In [ ]:
df_eth=df_eth.reset_index()
df_etc=df_etc.reset_index()

In [ ]:
df_eth["days"]=df_eth.index
df_eth.head()

   index       time  VtyDayRet30d  ...   GasLmtTxMean  Type  days
0    361 2016-07-25      0.064145  ...  116866.529623   eth     0
1    362 2016-07-26      0.069143  ...  106522.289666   eth     1
2    363 2016-07-27      0.071110  ...  126615.358103   eth     2
3    364 2016-07-28      0.065994  ...  133514.917908   eth     3
4    365 2016-07-29      0.065555  ...  139836.829202   eth     4

[5 rows x 9 columns]

In [ ]:
df_etc["days"]=df_etc.index
df_etc.head()

   index       time  VtyDayRet30d  ...   GasLmtTxMean  Type  days
0     35 2016-08-24      0.292737  ...  197837.042436   etc     0
1     36 2016-08-25      0.124512  ...  204431.309179   etc     1
2     37 2016-08-26      0.094313  ...  208950.209837   etc     2
3     38 2016-08-27      0.093886  ...  175090.831416   etc     3
4     39 2016-08-28      0.093662  ...  187384.163307   etc     4

[5 rows x 9 columns]

In [ ]:
df = pd.concat([df_eth, df_etc], axis=0)
df.head()

   index       time  VtyDayRet30d  ...   GasLmtTxMean  Type  days
0    361 2016-07-25      0.064145  ...  116866.529623   eth     0
1    362 2016-07-26      0.069143  ...  106522.289666   eth     1
2    363 2016-07-27      0.071110  ...  126615.358103   eth     2
3    364 2016-07-28      0.065994  ...  133514.917908   eth     3
4    365 2016-07-29      0.065555  ...  139836.829202   eth     4

[5 rows x 9 columns]

In [ ]:
df["etc"]=df["Type"].apply(lambda x: 1 if x=="etc" else 0)
df.head()

   index       time  VtyDayRet30d  ...  Type  days  etc
0    361 2016-07-25      0.064145  ...   eth     0    0
1    362 2016-07-26      0.069143  ...   eth     1    0
2    363 2016-07-27      0.071110  ...   eth     2    0
3    364 2016-07-28      0.065994  ...   eth     3    0
4    365 2016-07-29      0.065555  ...   eth     4    0

[5 rows x 10 columns]

### run the regression

Treatment: ETC hard-fork

In [ ]:
 import statsmodels.api as sm
 import statsmodels.formula.api as smf

In [ ]:
results = smf.ols('VtyDayRet30d ~ 1+ etc +days+TxTfrValAdjUSD+FeeMedUSD+RevUSD+GasLmtTxMean', data=df).fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           VtyDayRet30d   R-squared:                       0.090
Model:                            OLS   Adj. R-squared:                  0.089
Method:                 Least Squares   F-statistic:                     58.74
Date:                Sat, 26 Jun 2021   Prob (F-statistic):           1.41e-69
Time:                        07:36:46   Log-Likelihood:                 8145.7
No. Observations:                3562   AIC:                        -1.628e+04
Df Residuals:                    3555   BIC:                        -1.623e+04
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          0.0565      0.001     50.139      0.000       0.054       0.059
etc                0.0134      0.001     14.012      0.000       0.012       0.015
days            -4.71e-06    8.6e-07     -5.478      0.000    -6.4e-06   -3.02e-06
TxTfrValAdjUSD  2.556e-13   2.31e-13      1.105      0.269   -1.98e-13    7.09e-13
FeeMedUSD         -0.0046      0.001     -8.645      0.000      -0.006      -0.004
RevUSD           9.86e-10   1.14e-10      8.621      0.000    7.62e-10    1.21e-09
GasLmtTxMean    -2.78e-08   3.08e-09     -9.018      0.000   -3.38e-08   -2.18e-08
==============================================================================
Omnibus:                     1025.277   Durbin-Watson:                   0.079
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3402.475
Skew:                           1.437   Prob(JB):                         0.00
Kurtosis:                       6.829   Cond. No.                     1.06e+10
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.06e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
results = smf.ols('VtyDayRet30d ~ 1+ etc +days +etc*days+TxTfrValAdjUSD+FeeMedUSD+RevUSD+GasLmtTxMean', data=df).fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           VtyDayRet30d   R-squared:                       0.093
Model:                            OLS   Adj. R-squared:                  0.091
Method:                 Least Squares   F-statistic:                     52.14
Date:                Sat, 26 Jun 2021   Prob (F-statistic):           3.82e-71
Time:                        07:36:46   Log-Likelihood:                 8151.5
No. Observations:                3562   AIC:                        -1.629e+04
Df Residuals:                    3554   BIC:                        -1.624e+04
Df Model:                           7
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          0.0589      0.001     44.044      0.000       0.056       0.062
etc                0.0086      0.002      5.005      0.000       0.005       0.012
days            -7.93e-06   1.28e-06     -6.203      0.000   -1.04e-05   -5.42e-06
etc:days        5.818e-06   1.71e-06      3.399      0.001    2.46e-06    9.17e-06
TxTfrValAdjUSD  2.913e-13   2.31e-13      1.260      0.208   -1.62e-13    7.44e-13
FeeMedUSD         -0.0044      0.001     -8.267      0.000      -0.005      -0.003
RevUSD          9.961e-10   1.14e-10      8.720      0.000    7.72e-10    1.22e-09
GasLmtTxMean   -2.734e-08   3.08e-09     -8.873      0.000   -3.34e-08   -2.13e-08
==============================================================================
Omnibus:                     1008.176   Durbin-Watson:                   0.079
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3378.716
Skew:                           1.408   Prob(JB):                         0.00
Kurtosis:                       6.851   Cond. No.                     1.64e+10
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.64e+10. This might indicate that there are
strong multicollinearity or other numerical problems.